import { configureStore, createSlice } from '@reduxjs/toolkit';

const employeesSlice = createSlice({
	name: 'employees',
	initialState: {
		employees: [
			{
				id: Date.now() + 1,
				firstName: 'Alice',
				lastName: 'Dupont',
				dateOfBirth: '05/14/1985',
				startDate: '03/12/2022',
				department: 'Marketing',
				street: '123 Rue de Paris',
				city: 'Paris',
				state: 'FRANCE',
				ZIPCode: '75001',
			},
			{
				id: Date.now() + 2,
				firstName: 'Bob',
				lastName: 'Martin',
				dateOfBirth: '11/23/1990',
				startDate: '07/01/2021',
				department: 'Sales',
				street: '456 Boulevard Saint-Germain',
				city: 'Paris',
				state: 'FRANCE',
				ZIPCode: '75007',
			},
			{
				id: Date.now() + 3,
				firstName: 'Carla',
				lastName: 'Lemoine',
				dateOfBirth: '02/29/1988',
				startDate: '09/15/2023',
				department: 'Legal',
				street: '789 Avenue de la République',
				city: 'Lille',
				state: 'FRANCE',
				ZIPCode: '59000',
			},
			{
				id: Date.now() + 4,
				firstName: 'David',
				lastName: 'Dupuis',
				dateOfBirth: '12/05/1992',
				startDate: '06/20/2022',
				department: 'Engineering',
				street: '321 Rue des Fleurs',
				city: 'Lyon',
				state: 'FRANCE',
				ZIPCode: '69000',
			},
			{
				id: Date.now() + 5,
				firstName: 'Eva',
				lastName: 'Benoît',
				dateOfBirth: '07/19/1987',
				startDate: '05/10/2023',
				department: 'Human Resources',
				street: '654 Route de Lyon',
				city: 'Marseille',
				state: 'FRANCE',
				ZIPCode: '13001',
			},
			{
				id: Date.now() + 6,
				firstName: 'Frank',
				lastName: 'Muller',
				dateOfBirth: '08/15/1982',
				startDate: '01/25/2022',
				department: 'Engineering',
				street: '987 Avenue du Prado',
				city: 'Marseille',
				state: 'FRANCE',
				ZIPCode: '13008',
			},
			{
				id: Date.now() + 7,
				firstName: 'Gina',
				lastName: 'Moreau',
				dateOfBirth: '04/10/1995',
				startDate: '11/01/2023',
				department: 'Customer Support', // Adjusted to 'Marketing'
				street: '321 Avenue de la Liberté',
				city: 'Nice',
				state: 'FRANCE',
				ZIPCode: '06000',
			},
			{
				id: Date.now() + 8,
				firstName: 'Hugo',
				lastName: 'Roux',
				dateOfBirth: '09/22/1980',
				startDate: '08/14/2021',
				department: 'Sales',
				street: '456 Rue de la Gare',
				city: 'Toulouse',
				state: 'FRANCE',
				ZIPCode: '31000',
			},
			{
				id: Date.now() + 9,
				firstName: 'Isabelle',
				lastName: 'Giraud',
				dateOfBirth: '03/18/1991',
				startDate: '10/30/2022',
				department: 'Legal',
				street: '789 Boulevard de la Mer',
				city: 'Bordeaux',
				state: 'FRANCE',
				ZIPCode: '33000',
			},
			{
				id: Date.now() + 10,
				firstName: 'John',
				lastName: 'Cohen',
				dateOfBirth: '10/05/1986',
				startDate: '02/20/2022',
				department: 'Sales',
				street: '123 Rue de la République',
				city: 'Strasbourg',
				state: 'FRANCE',
				ZIPCode: '67000',
			},
			{
				id: Date.now() + 11,
				firstName: 'Katia',
				lastName: 'Renaud',
				dateOfBirth: '06/25/1994',
				startDate: '12/15/2022',
				department: 'Marketing',
				street: '456 Avenue des Champs-Élysées',
				city: 'Paris',
				state: 'FRANCE',
				ZIPCode: '75008',
			},
			{
				id: Date.now() + 12,
				firstName: 'Louis',
				lastName: 'Lacroix',
				dateOfBirth: '01/10/1984',
				startDate: '04/05/2022',
				department: 'Engineering',
				street: '789 Rue de la Paix',
				city: 'Nantes',
				state: 'FRANCE',
				ZIPCode: '44000',
			},
			{
				id: Date.now() + 13,
				firstName: 'Marie',
				lastName: 'Dubois',
				dateOfBirth: '11/30/1993',
				startDate: '09/01/2022',
				department: 'Marketing',
				street: '321 Boulevard de l’Innovation',
				city: 'Rennes',
				state: 'FRANCE',
				ZIPCode: '35000',
			},
			{
				id: Date.now() + 14,
				firstName: 'Nicolas',
				lastName: 'Bertrand',
				dateOfBirth: '02/14/1990',
				startDate: '07/15/2023',
				department: 'Finance', // Adjusted to 'Human Resources'
				street: '654 Rue de l’Industrie',
				city: 'Lille',
				state: 'FRANCE',
				ZIPCode: '59800',
			},
			{
				id: Date.now() + 15,
				firstName: 'Olivia',
				lastName: 'Marty',
				dateOfBirth: '12/01/1992',
				startDate: '05/23/2023',
				department: 'Sales',
				street: '987 Avenue du Général Leclerc',
				city: 'Aix-en-Provence',
				state: 'FRANCE',
				ZIPCode: '13100',
			},
			{
				id: Date.now() + 16,
				firstName: 'Paul',
				lastName: 'Dufresne',
				dateOfBirth: '07/12/1989',
				startDate: '03/30/2022',
				department: 'Marketing', // Adjusted to 'Marketing'
				street: '123 Route de la Mer',
				city: 'Antibes',
				state: 'FRANCE',
				ZIPCode: '06600',
			},
			{
				id: Date.now() + 17,
				firstName: 'Quentin',
				lastName: 'Jacques',
				dateOfBirth: '09/29/1990',
				startDate: '06/12/2023',
				department: 'Marketing', // Adjusted to 'Marketing'
				street: '456 Rue de la Liberté',
				city: 'Clermont-Ferrand',
				state: 'FRANCE',
				ZIPCode: '63000',
			},
			{
				id: Date.now() + 18,
				firstName: 'Renee',
				lastName: 'Lemoine',
				dateOfBirth: '03/22/1988',
				startDate: '01/10/2023',
				department: 'Engineering',
				street: '789 Boulevard de l’Opéra',
				city: 'Toulon',
				state: 'FRANCE',
				ZIPCode: '83000',
			},
		],
	},
	reducers: {
		addEmployee: (state, action) => {
			state.employees.push(action.payload);
		},
	},
});

export const { addEmployee } = employeesSlice.actions;

export const store = configureStore({
	reducer: {
		employees: employeesSlice.reducer,
	},
});
